
[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[mouse]
hide_when_typing = true

[window]
decorations = "full"
dynamic_title = true

[window.padding]
x = 4
y = 4

[window.dimensions]
columns = 135
lines = 35

[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]
